<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.github.marcoshssilva</groupId>
    <artifactId>cloud-api-controller-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../cloud-api-controller-parent/pom.xml</relativePath>
  </parent>
  <artifactId>cloud-api-controller-web</artifactId>
  <name>cloud-api-controller-web</name>
  <version>${revision}</version>
  <url>https://marcosilva.dev</url>
  <dependencies>
    <!-- Undertow Web Server -->
    <dependency>
      <groupId>io.undertow</groupId>
      <artifactId>undertow-core</artifactId>
      <version>2.3.18.Final</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>